import api from "./api";
import axios from "axios";

/**
 * Uploads a file directly to Cloudinary using a signature generated by the backend.
 * Returns the secure URL of the uploaded image.
 */
export async function uploadImageToCloudinary(file: File): Promise<string> {
  // 1. Fetch Cloudinary signed upload parameters from the backend
  const response = await api.get("/api/products/cloudinary-signature/");
  const { signature, timestamp, cloud_name, api_key, folder } = response.data;

  // 2. Build the FormData payload for Cloudinary
  const formData = new FormData();
  formData.append("file", file);
  formData.append("api_key", api_key);
  formData.append("timestamp", timestamp.toString());
  formData.append("signature", signature);
  formData.append("folder", folder);

  const cloudinaryUrl = `https://api.cloudinary.com/v1_1/${cloud_name}/image/upload`;

  // 3. Upload using raw axios to avoid transmitting backend auth tokens
  const uploadResponse = await axios.post(cloudinaryUrl, formData, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
  });

  if (!uploadResponse.data || !uploadResponse.data.secure_url) {
    throw new Error("Failed to retrieve secure URL from Cloudinary upload response");
  }

  return uploadResponse.data.secure_url;
}
